facebook/xcbuild

CMakeLists.txt, Libraries/builtin/Sources/copyPlist/Driver.cpp, Libraries/builtin/Sources/copyStrings/Driver.cpp, Libraries/builtin/Sources/infoPlistUtility/Driver.cpp, Libraries/dependency/Tools/dependency-info-tool.cpp, Libraries/libutil/Headers/libutil/Subprocess.h, Libraries/pbxbuild/Headers/pbxbuild/Tool/OptionsResult.h, Libraries/pbxbuild/Sources/FileTypeResolver.cpp, Libraries/pbxbuild/Sources/Tool/Tokens.cpp, Libraries/pbxbuild/Tools/dump_hmap.cpp, Libraries/pbxsetting/Sources/Condition.cpp, Libraries/pbxsetting/Sources/Value.cpp, Libraries/pbxspec/Headers/pbxspec/PBX/BuildRule.h, Libraries/plist/Headers/plist/Format/Format.h, Libraries/plist/Sources/Format/ABPWriter.cpp, Libraries/plist/Tools/plutil.cpp, Libraries/xcexecution/Sources/NinjaExecutor.cpp, Libraries/xcexecution/Sources/SimpleExecutor.cpp, Libraries/xcsdk/CMakeLists.txt
I'm working on building xcbuild on some centOS machines with GCC 4.8/4.9 installed.  Upgrading GCC to 5.0 isn't an option since I don't control the packaging available, so I opted to make xcbuild happily build instead.
=> Build with GCC 4.8/4.9

Libraries/plist/Tools/plutil.cpp
Standard practice is to return 0 for success.
=> Return 0 for success in plutil

Libraries/libutil/Sources/Filesystem.cpp, Libraries/libutil/Tests/test_MemoryFilesystem.cpp, Libraries/xcassets/Sources/Asset/Asset.cpp, Libraries/xcexecution/Sources/Parameters.cpp, Libraries/xcscheme/Sources/SchemeGroup.cpp, Libraries/xcsdk/Sources/SDK/Manager.cpp, Libraries/xcsdk/Sources/SDK/Platform.cpp
Several calls to Filesystem::enumerateDirectory gave a
function with the wrong return type. Change the return type
of these functions from 'bool' to 'void' to satisfy the
signature of enumerateDirectory.
=> Fix broken calls to Filesystem::enumerateDirectory

CMakeLists.txt
Use the new form of add_test which properly maps target
names to executable paths. This fixes running 'ctest' to run
all tests.
=> Fix CTest support

.travis.yml, README.md
pkg-config is needed on Linux in order for CMake to detect
libxml2. Apparently, Travis has it installed by default, but
be explicit about our dependencies for further developers.
=> Explicitly install pkg-config on Linux for Travis

CMakeLists.txt, Libraries/pbxbuild/Sources/DerivedDataHash.cpp, Libraries/pbxspec/Sources/Manager.cpp, Libraries/plist/Sources/Format/ABPWriter.cpp
Drop GCC's -fno-strict-aliasing and fix the bugs caught by
GCC's diagnostics. (GCC's diagnostics only trigger if
CMAKE_BUILD_TYPE is Release, not Debug.) Verified with GCC
6.1.1 on Ubuntu 14.04.
=> Don't aliasing types improperly

Libraries/libutil/Sources/Subprocess.cpp, Libraries/libutil/Sources/SysUtil.cpp, Libraries/plist/Sources/Format/XMLWriter.cpp
Building GCC 6.1.1 on Ubuntu 14.04  detected two errors:
* The return values of some APIs were not checked, and
* The result of some variables were not used.
Fix these errors, allowing GCC 6 to build all of xcbuild.
=> Fix compilation with GCC 6 on Ubuntu

Libraries/acdriver/Headers/acdriver/Result.h, Libraries/builtin/Sources/copyStrings/Driver.cpp, Libraries/libutil/Headers/libutil/Base.h, Libraries/pbxbuild/Sources/FileTypeResolver.cpp, Libraries/xcdriver/Sources/ListAction.cpp, Libraries/xcsdk/Sources/SDK/Manager.cpp, Libraries/xcworkspace/Tools/dump_xcworkspace.cpp
For whatever reason, xcbuild couldn't find unique_ptr, strcmpcase, and other basic std:: functionality unless I included the headers.
=> [xcbuild] Fixes to build on Linux

Libraries/acdriver/Headers/acdriver/CompileActionImageSet.h, Libraries/acdriver/Headers/acdriver/CompileOutput.h, Libraries/acdriver/Sources/CompileAction.cpp, Libraries/acdriver/Sources/CompileActionImageSet.cpp
- Refactor some logic out into separate functions.
- Cleanup code style nits for consistency.
- Use filesystem to read JPEG images as well as PNG.
- Move image set compilation into namespace and class.
=> Minor cleanups to image set compilation.

Libraries/acdriver/Sources/Compile/AppIconSet.cpp, Libraries/acdriver/Sources/CompileAction.cpp
Supports copying the images and writing the icon metadata to info
plist additions. Current implementation has two limitations:
- All idioms are copied for all target platforms. For example, watch images are copied for asset compilation targeting a phone.
- The size of images is not verified against the specified dimensions.
=> Support compiling app icon sets.

README.md
The old URL https://martine.github.io/ninja now 404's.
=> Fix outdated Ninja link in README.md

Libraries/xcsdk/Headers/xcsdk/SDK/Target.h, Libraries/xcsdk/Tools/xcrun.cpp
Test plan:
/path/to/xcbuild/bin/xcrun --sdk iphoneos --show-sdk-version
9.2
Before it would print out the name of the SDK.
=> [xcsdk] Properly print out the SDK version when asked

Libraries/acdriver/Sources/CompileAction.cpp, Libraries/libbom/Headers/bom/bom.h, Libraries/libbom/Sources/bom.c, Libraries/libbom/Sources/bom_tree.c, Libraries/libcar/Headers/car/Reader.h, Libraries/libcar/Headers/car/Writer.h, Libraries/libcar/Sources/Writer.cpp, Libraries/libcar/Tests/test_Writer.cpp
Avoid memmoves in the libbom by optionally preallocating space for the indexes
Allow raw reads and writes of rendition key-value pairs
Allow specifying the key format to the writer
=> Make reading and writing CAR files faster

Libraries/plist/CMakeLists.txt
The directory is always present even if the submodule is not checked
out. This checks for the source file being present and uses that
instead.
=> Fix builds without linenoise

CMakeLists.txt, Libraries/graphics/CMakeLists.txt, Libraries/plist/CMakeLists.txt
The project won't build without libpng anyway. Make it fatal in cmake
instead of hiding the failure and letting the build step fail instead.
=> Make libpng a required library

Libraries/xcexecution/Sources/NinjaExecutor.cpp
If the generator itself (xcbuild) changes, we should regenerate the
ninja files too.
=> Regenerate when the xcbuild binary changes

Libraries/pbxbuild/Sources/Tool/LinkerResolver.cpp
If we don't do this correctly, we might end up picking the wrong library
to link against. This happened when building an app that has its own
copy of protobuf. `libprotobuf.tbd` from `iPhoneOS.sdk` was used instead
of `libprotobuf.a` from the app itself.
=> Preserve ordering of library search paths

Libraries/libcar/Sources/Rendition.cpp
When build xcbuild with -NDEBUG, assert() is compiled out and, to the compiler,
the 'algorithm' variable has the potential to be uninitialized. Refactor the code
so it compiles cleanly.
=> [Rendition] Make sure 'algorithm' is initialized for release builds

Libraries/process/CMakeLists.txt
=> Link required libraries when using threading functions. Fixes #139.

Libraries/acdriver/Headers/acdriver/Options.h, Libraries/acdriver/Sources/CompileAction.cpp, Libraries/acdriver/Sources/Options.cpp
Having the option to customize the output path fully (not just the directory) is helpful in cases where the archives are being pre-generated, or there are multiple going into the same directory.
=> [actool] Add --compile-output-filename option for specifying car filename

Libraries/process/Sources/DefaultContext.cpp
h/t to @sas for this fix. This is a minimal fix for my problems when
using xcbuild tools on my Linux machine.
See https://github.com/facebook/xcbuild/issues/138
=> [process] Don't use the constructor attribute on Linux for grabbing command line arguments

Libraries/libcar/Headers/car/car_format.h, Libraries/libcar/Sources/Writer.cpp
Looks like the key format is also little-endian.
Fixes the issue:
```
CoreUI:  Car file has erroneous key format information. Using CUISystemThemeRenditionKeyFormat
```
as well as the subsequent buffer overflow when reading the compiled car file.
=> [actool] Fix car header key format in car writer

Libraries/xcsdk/Sources/SDK/Toolchain.cpp
Alternative keychains such as the Swift nightly use an updated plist file, renamed to Info.plist.
=> Support Info.plist in Toolchains

Libraries/builtin/Sources/infoPlistUtility/Driver.cpp, Libraries/pbxbuild/Sources/Target/Environment.cpp, Libraries/plist/Sources/String.cpp, Libraries/xcdriver/Sources/ShowSDKsAction.cpp, Libraries/xcdriver/Sources/VersionAction.cpp, Libraries/xcsdk/Headers/xcsdk/SDK/Platform.h, Libraries/xcsdk/Headers/xcsdk/SDK/PlatformVersion.h, Libraries/xcsdk/Headers/xcsdk/SDK/Product.h, Libraries/xcsdk/Headers/xcsdk/SDK/Target.h, Libraries/xcsdk/Headers/xcsdk/SDK/Toolchain.h, Libraries/xcsdk/Sources/Configuration.cpp, Libraries/xcsdk/Sources/SDK/Platform.cpp, Libraries/xcsdk/Sources/SDK/PlatformVersion.cpp, Libraries/xcsdk/Sources/SDK/Product.cpp, Libraries/xcsdk/Sources/SDK/Target.cpp, Libraries/xcsdk/Sources/SDK/Toolchain.cpp, Libraries/xcsdk/Tests/test_Manager.cpp, Libraries/xcsdk/Tests/test_PlatformVersion.cpp, Libraries/xcsdk/Tools/xcrun.cpp
- Warn about missing keys when parsing; add currently missing keys.
- Use optionals to avoid unsafely assuming parsed values always exist.
- Update style to match other libraries.
=> Modernize and complete SDK loading.

Specifications/FileType/CMakeLists.txt
Three files were missing: abstreactassetcatalog.xcspec, file.swiftpm-manifest.xcspec, and folder.stickers.xcspec
=> Add new files to CMakeLists.txt

Libraries/libcar/Headers/car/car_format.h, Libraries/libcar/Sources/Reader.cpp, Libraries/libcar/Sources/Rendition.cpp, Libraries/libcar/Sources/car_format.c
The extra metadata section stores a string with contextual info
on how the asset archive was compiled, especially when the archive
is stripped to target certain devices or platforms.
Other new fields correspond to new asset document format fields.
=> Add definitions for some newer asset archive format fields.

Libraries/acdriver/Headers/acdriver/Options.h, Libraries/acdriver/Sources/CompileAction.cpp, Libraries/acdriver/Sources/Options.cpp
They are parsed but not yet used during compilation.
=> Add a few missing asset catalog compiler driver options.

Libraries/builtin/Sources/infoPlistUtility/Driver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderCommon.cpp
if the option is not found and resolves to empty string,
it will have dangling -mininum-deployment-target option without value
and fail
=> Be safe when putting -mininum-deployment-target option

Libraries/pbxbuild/Sources/Tool/LinkerResolver.cpp
linkers in other platforms won't have this option
=> Put linker option "-dependency_info $(dependency_info_file)" only on darwin

Libraries/pbxspec/Sources/Manager.cpp
Prevents a warning about duplicate specifications on start.
=> Adjust loaded platform specifications for additional domains.

Libraries/pbxbuild/Headers/pbxbuild/Tool/Context.h, Libraries/pbxbuild/Headers/pbxbuild/Tool/Invocation.h, Libraries/pbxbuild/Sources/Phase/PhaseInvocations.cpp, Libraries/pbxbuild/Sources/Tool/AssetCatalogResolver.cpp, Libraries/pbxbuild/Sources/Tool/ClangResolver.cpp, Libraries/pbxbuild/Sources/Tool/Context.cpp, Libraries/pbxbuild/Sources/Tool/CopyResolver.cpp, Libraries/pbxbuild/Sources/Tool/DittoResolver.cpp, Libraries/pbxbuild/Sources/Tool/InfoPlistResolver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderResolver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderStoryboardLinkerResolver.cpp, Libraries/pbxbuild/Sources/Tool/Invocation.cpp, Libraries/pbxbuild/Sources/Tool/LinkerResolver.cpp, Libraries/pbxbuild/Sources/Tool/MakeDirectoryResolver.cpp, Libraries/pbxbuild/Sources/Tool/ScriptResolver.cpp, Libraries/pbxbuild/Sources/Tool/SwiftResolver.cpp, Libraries/pbxbuild/Sources/Tool/SwiftStandardLibraryResolver.cpp, Libraries/pbxbuild/Sources/Tool/SymlinkResolver.cpp, Libraries/pbxbuild/Sources/Tool/ToolResolver.cpp, Libraries/pbxbuild/Sources/Tool/TouchResolver.cpp, Libraries/xcexecution/Headers/xcexecution/NinjaExecutor.h, Libraries/xcexecution/Sources/NinjaExecutor.cpp, Libraries/xcexecution/Sources/SimpleExecutor.cpp
Rather than looking at the filesystem to find an executable path at
configuration time, find the executable at execution time. This allows
different executors to handle searching for paths differently (for
example, using internal or external builtin tools), and avoids using
the filesystem during configuration.
=> Delay resolving executable paths until execution time.

Libraries/plist/Sources/Format/ASCIIPListLexer.cpp, Libraries/plist/Tests/Format/test_JSON.cpp
Using a JSON parser test suite, refine number and key parsing to match
the JSON specification. Remaining issues are related to Unicode support,
escape sequences, and trailing commas.
The last of those is intentionally non-conforming for compatibility.
=> Improve JSON parsing to handle more edge cases.

Libraries/builtin/CMakeLists.txt, Libraries/builtin/Tests/test_copyPlist.cpp, Libraries/builtin/Tests/test_copyStrings.cpp
Tests basic functionality of copying multiple property lists while
converting them to a standard format.
=> Add unit test for property list copy built-in utility.

Specifications/Tool/com.apple.compilers.pbxcp.xcspec
pbx cp command should specify output dir, not the output file path.
=> fix builtin pbxcp

Libraries/acdriver/Headers/acdriver/Options.h, Libraries/acdriver/Sources/CompileAction.cpp, Libraries/acdriver/Sources/Options.cpp, Libraries/pbxbuild/Sources/Phase/Context.cpp, Libraries/pbxbuild/Sources/Tool/AssetCatalogResolver.cpp, Specifications/Compiler/com.apple.compilers.assetcatalog.xcspec
Asset catalog compilation now uses a custom variable to pass inputs
to the specification, and a custom grouping method to group inputs.
Does not pass sticker pack translations to asset catalog compiler,
as this seems to require parsing the asset catalog just to determine
which strings files should be used. Left as a future task.
=> Partially update asset catalog compiler specification and resolver.

Libraries/libutil/Sources/DefaultFilesystem.cpp
createDirectory entered an infinite loop breaking xcbuild.
I was looking into adding tests for this but I can't figure out how to do that safely. There should be some way to create a container in CTest so we can write the tests just like those for MemoryFilesystem.
=> Prevent infinite loop in createDirectory.

Libraries/pbxbuild/Sources/Phase/File.cpp
Previously it was by default always set, but to an empty string.
This avoids having an empty outputBaseName later in ClangResolver,
which caused the output object files be named ".o" for all input
source files.
=> Make fileNameDisambiguator optional in File::ResolveBuildFiles

Libraries/xcsdk/Sources/SDK/Platform.cpp
I believe DEPLOYMENT_TARGET_CLANG_FLAG_ENV should actually be DEPLOYMENT_TARGET_CLANG_ENV_NAME?
=> deployment target version env name fix

Libraries/libutil/Sources/DefaultFilesystem.cpp
A path like "foo/bar/baz" will end up looking for a directory
named "" unless any of the earlier directories already exist.
=> Fix recursive createDirectory for relative paths

Libraries/libutil/Sources/Permissions.cpp
abort() requires #include <stdlib.h>
=> add include for stdlib.h for abort()

Libraries/pbxbuild/Headers/pbxbuild/Build/Environment.h, Libraries/pbxbuild/Sources/Build/Environment.cpp, Libraries/pbxbuild/Sources/Target/Environment.cpp, Libraries/pbxbuild/Sources/Tool/AssetCatalogResolver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderResolver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderStoryboardLinkerResolver.cpp, Libraries/pbxbuild/Sources/Tool/OptionsResult.cpp, Libraries/xcexecution/Sources/NinjaExecutor.cpp, Libraries/xcexecution/Sources/SimpleExecutor.cpp, Libraries/xcsdk/Sources/SDK/Manager.cpp, Libraries/xcsdk/Sources/SDK/Platform.cpp, Libraries/xcsdk/Sources/SDK/Toolchain.cpp
- Include all necessary paths in tool search paths.
- Set `PATH` to match the paths searched for tools.
- Set `DEVELOPER_DIR` for all invocations to stay self-contained.
- Pass along process environment to tools rather than clearing.
My version of #169. @onhachoe, would be great if you could test with the case you were seeing `PATH` being important.
=> Pass correct environment to tools.

Libraries/dependency/Tools/dependency-info-tool.cpp
sometimes we'd want to depend on a single file, not entire directory
subtree.
rename DirectoryDependnecyInfo to PathDependencyInfo and make it
handle both cases.
=> ignore non-directory path in dependency-info-tool

Libraries/plist/Sources/Format/ABPReader.cpp
This is implementation-defined rather than undefined behavior.
=> Use memcpy to transmute floating point values.

Libraries/libbom/Sources/bom.c
Some of the vars->first were changed to vars + sizeof(struct bom_variable) in #202
where it really had to be sizeof(struct bom_variables)
=> Fix bom variable offset.

Libraries/pbxsetting/Sources/XC/Config.cpp
Currently, build file parsing would break when encounterd with something like
// some comment //
fix this.
=> Fix xcode build file parsing

Libraries/libutil/Sources/MemoryFilesystem.cpp
`path` was being shadowed and not used.  Remove unused lambda capture.
NFC.
=> Remove unused lambda capture

Libraries/pbxspec/Headers/pbxspec/Manager.h, Libraries/pbxspec/Headers/pbxspec/PBX/Specification.h, Libraries/pbxspec/Sources/Manager.cpp, Libraries/pbxspec/Sources/PBX/Specification.cpp, Libraries/process/Sources/DefaultContext.cpp
This had the nasty side effect of breaking with a stack overflow when a `foo:identifier`
xcspec was `BasedOn` a `bar:identifier` xcspec. We were not enforcing the domain,
which meant we kept inheriting from ourselves over and over.
=> Grab specifications from the correct domain

Libraries/dependency/Tools/dependency-info-tool.cpp
Instead of returning a mixture of 0, -1, and booleans, use standard
definitions from stdlib.
This fixes issue #238.
=> Fix return codes in dependency-info-tool

Libraries/plist/Tools/PlistBuddy.cpp
Make PlistBuddy's merge operation skip duplicate keys to be inline with behavior of reference tool.
=> [PlistBuddy] skip duplicate keys during merge.

Libraries/pbxbuild/Headers/pbxbuild/Tool/Invocation.h, Libraries/pbxbuild/Headers/pbxbuild/Tool/SwiftModuleInfo.h, Libraries/pbxbuild/Sources/Phase/PhaseInvocations.cpp, Libraries/pbxbuild/Sources/Phase/SourcesResolver.cpp, Libraries/pbxbuild/Sources/Phase/SwiftResolver.cpp, Libraries/pbxbuild/Sources/Target/Environment.cpp, Libraries/pbxbuild/Sources/Tool/ClangResolver.cpp, Libraries/pbxbuild/Sources/Tool/Invocation.cpp, Libraries/xcexecution/Headers/xcexecution/NinjaExecutor.h, Libraries/xcexecution/Sources/NinjaExecutor.cpp, Libraries/xcsdk/Sources/SDK/Toolchain.cpp, Specifications/Tool/CMakeLists.txt, Specifications/Tool/com.apple.build-tools.swift-stdlib-tool.xcspec
This includes 4 commits
Compile swift before any other clang invocation
- Swift compilation first before objc compilation.
- Fixes issue address on #237 
Slight refactoring of PhaseInvocation resolving step
- as title
Refactor builtin tool resolving in NinjaExecutor
- Fixes to make symlinked xcbuild work properly
Refactor auxiliary file creation path for ninja
- Auxiliary file handling improvements.
Add Swift Standard Library tool xcspec
- swift-stdlib-tool xcspec to copy over swift libraries
=> Fixes to make swift project work correctly and fixes to ninja execution path.

Libraries/dependency/Tests/test_DirectoryDependencyInfo.cpp, Libraries/libutil/Sources/DefaultFilesystem.cpp, Libraries/libutil/Sources/MemoryFilesystem.cpp, Libraries/libutil/Tests/test_MemoryFilesystem.cpp
This fixes case when Filesystem->removeDirectory() call is invoked with recursive option set to true.
=> Process contents inside child directories first in Filesystem->readDirectory call

Libraries/pbxbuild/Headers/pbxbuild/Tool/Context.h, Libraries/pbxbuild/Headers/pbxbuild/Tool/Invocation.h, Libraries/pbxbuild/Sources/Phase/PhaseInvocations.cpp, Libraries/pbxbuild/Sources/Tool/AssetCatalogResolver.cpp, Libraries/pbxbuild/Sources/Tool/ClangResolver.cpp, Libraries/pbxbuild/Sources/Tool/Context.cpp, Libraries/pbxbuild/Sources/Tool/CopyResolver.cpp, Libraries/pbxbuild/Sources/Tool/DittoResolver.cpp, Libraries/pbxbuild/Sources/Tool/InfoPlistResolver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderResolver.cpp, Libraries/pbxbuild/Sources/Tool/InterfaceBuilderStoryboardLinkerResolver.cpp, Libraries/pbxbuild/Sources/Tool/LinkerResolver.cpp, Libraries/pbxbuild/Sources/Tool/MakeDirectoryResolver.cpp, Libraries/pbxbuild/Sources/Tool/ScriptResolver.cpp, Libraries/pbxbuild/Sources/Tool/SwiftResolver.cpp, Libraries/pbxbuild/Sources/Tool/SwiftStandardLibraryResolver.cpp, Libraries/pbxbuild/Sources/Tool/SymlinkResolver.cpp, Libraries/pbxbuild/Sources/Tool/ToolResolver.cpp, Libraries/pbxbuild/Sources/Tool/TouchResolver.cpp, Libraries/xcexecution/Sources/NinjaExecutor.cpp, Libraries/xcexecution/Sources/SimpleExecutor.cpp
Currently, we are munging all invocations within a target and don't setup execution order based on phase ordering.
This creates problem when build phases are set up in a way to executed in specific ordering.
Prioritize all invocations with respect to their phase ordering, so that executions are done in order their phases are defined.
=> Make build order respect phase ordering on build target.

Libraries/libutil/Sources/DefaultFilesystem.cpp
Only one of the two last arguments to these functions can be null, not
both. This works on Windows 10 but crashes on Windows 7.
This fixes issue #269.
=> Fix calls to ReadFile and WriteFile on Windows pre-10

Libraries/libcar/Sources/AttributeList.cpp
When building libcar for Windows, the array size calculation would be of type
`unsigned long long` (aka `size_t`).  However, `identifier` is of type
`enum car_attribute_identifier` (aka `int`).  This results in a warning due to
the sign mismatch.  Perform an explicit cast to the size type for the
comparision to silence the warning.
Take the opportunity to move the constant expression of the array length into a
variable for ease of readability.
=> libcar: silence a -Wsign-compare warning

Libraries/xcassets/Headers/xcassets/Slot/SystemVersion.h
while fixing #274, I noticed that xcbuild fails to build from source, at least on an up-to-date Debian/sid system, with the following error
~~~
../Libraries/xcassets/Headers/xcassets/Slot/SystemVersion.h:35:13: error: In the GNU C Library, "major" is defined
by <sys/sysmacros.h>. For historical compatibility, it is
currently defined by <sys/types.h> as well, but we plan to
remove this soon. To use "major", include <sys/sysmacros.h>
directly. If you did not intend to use a system-defined macro
"major", you should undefine it after including <sys/types.h>. [-Werror]
int major() const
^~~~~~~~~ …
=> undefine major/minor macros to prevent build failures with newer glibc

Libraries/xcdriver/Sources/Driver.cpp, Libraries/xcdriver/Sources/Usage.cpp
this PR makes `xcbuild` dump the usage-information if it encounters an error while parsing the cmdline args (mostly this will be because the user passed unknown flags)
=> print usage information for wrong arguments

Libraries/acdriver/CMakeLists.txt, Libraries/acdriver/Headers/acdriver/Compile/Output.h, Libraries/acdriver/Headers/acdriver/NonStandard.h, Libraries/acdriver/Headers/acdriver/Options.h, Libraries/acdriver/Sources/Compile/ImageSet.cpp, Libraries/acdriver/Sources/Compile/Output.cpp, Libraries/acdriver/Sources/CompileAction.cpp, Libraries/acdriver/Sources/NonStandard.cpp, Libraries/acdriver/Sources/Options.cpp, Libraries/libcar/Headers/car/Rendition.h, Libraries/libcar/Headers/car/car_format.h, Libraries/libcar/Sources/Rendition.cpp
Adding the capability to pack WEBP images into compiled assets catalog.
Since this is not standard behavior, I'm adding it under `--allows-image-types webp`.
This way (`--allows-image-types`) also makes it easier to add future new extension types.
Since this is not a feature supported by Apple's Xcode.actool, I'm also adding `--allow-extensions` as well, that makes it explicit it's incompatible behavior.
=> Add --allow-non-standard-behavior and --allow-image-type webp to actool

Libraries/acdriver/Tests/test_AppIconSet.cpp, Libraries/libutil/Headers/libutil/DefaultFilesystem.h, Libraries/libutil/Headers/libutil/FSUtil.h, Libraries/libutil/Headers/libutil/Filesystem.h, Libraries/libutil/Headers/libutil/MemoryFilesystem.h, Libraries/libutil/Headers/libutil/Relative.h, Libraries/libutil/Sources/DefaultFilesystem.cpp, Libraries/libutil/Sources/FSUtil.cpp, Libraries/libutil/Sources/MemoryFilesystem.cpp, Libraries/libutil/Sources/Relative.cpp, Libraries/libutil/Tests/test_FSUtil.cpp, Libraries/pbxbuild/Sources/Target/Environment.cpp, Libraries/process/Headers/process/Context.h, Libraries/process/Headers/process/DefaultContext.h, Libraries/process/Headers/process/MemoryContext.h, Libraries/process/Sources/DefaultContext.cpp, Libraries/process/Sources/MemoryContext.cpp, Libraries/xcdriver/Sources/FindAction.cpp, Libraries/xcdriver/Sources/VersionAction.cpp, Libraries/xcsdk/Headers/xcsdk/SDK/Manager.h, Libraries/xcsdk/Sources/Environment.cpp, Libraries/xcsdk/Sources/SDK/Manager.cpp, Libraries/xcsdk/Sources/SDK/Target.cpp, Libraries/xcsdk/Tools/xcrun.cpp
Several changes here:
- Filesystem::readSymbolicLink() now behaves like "readlink -f", so links will be
thoroughly resolved.
- The SDK Manager will now try to resolve toolchains and SDKs passed its
way using a FS object.  Most locations have been stubbed with a
nullptr for the FS since those are internally-provided toolchain names
/ paths, but some locations that can take in user-provided input are
different.
- I added some functionality to convert a path into a vector of
components; I use this to iterate though a given path and invoke
"readlink()" per step.
=> Allow symlinked paths when passing an SDK to xcrun
