Libraries/builtin/Tests/test_copyStrings.cpp
Libraries/plist/CMakeLists.txt

With these changes, I'm able to build xcbuild with my setup and,
perhaps importantly, run one of the tools that uses libxml.

Build with GCC 4.9 on Centos7

---

Libraries/pbxbuild/Sources/Phase/ProductTypeResolver.cpp

The `INFOPLIST_PREPROCESS` build setting requests preprocessing of
the Info.plist file before standard processing. Fixes #77.

Support preprocessing Info.plist before the Info.plist utility.

---

Libraries/acdriver/CMakeLists.txt
Libraries/acdriver/Headers/acdriver/CompileOutput.h
Libraries/acdriver/Sources/CompileOutput.cpp
Libraries/acdriver/Tests/test_CompileOutput.cpp

Add asset catalog driver compile action output.

---

Libraries/acdriver/Headers/acdriver/Compile/Convert.h
Libraries/acdriver/Sources/Compile/Convert.cpp
Libraries/acdriver/Sources/Compile/LaunchImage.cpp
Libraries/xcassets/CMakeLists.txt
Libraries/xcassets/Headers/xcassets/Asset/LaunchImage.h
Libraries/xcassets/Headers/xcassets/Slot/SystemVersion.h
Libraries/xcassets/Sources/Asset/LaunchImage.cpp
Libraries/xcassets/Sources/Slot/ImageSize.cpp
Libraries/xcassets/Sources/Slot/SystemVersion.cpp
Libraries/xcassets/Tests/test_ImageSize.cpp
Libraries/xcassets/Tests/test_SystemVersion.cpp

Support compiling launch image assets.

Compile launch image assets.

---

Specifications/BuildPhase/CMakeLists.txt
Specifications/FileType/CMakeLists.txt

I can't install xcbuild because of these specification errors.  I've no idea what they should actually be named, but this works for me.

Installation fixes

---

Libraries/plist/Tools/PlistBuddy.cpp

Summary: For each of the PlistBuddy subcommands, on false, return '1' exit code.
Test Plan:
Ran PlistBuddy -c "Print :BogusKeyThatDoesntExist"  /tmp/app.plist
echo $?

[xcbuild] Make PlistBuddy return a non-zero code on error

---

Libraries/xcsdk/CMakeLists.txt
Libraries/xcsdk/Headers/xcsdk/SDK/Toolchain.h
Libraries/xcsdk/Sources/SDK/Manager.cpp
Libraries/xcsdk/Sources/SDK/Toolchain.cpp
Libraries/xcsdk/Tests/test_Toolchain.cpp

Unit test for toolchain info parsing.

---

Libraries/plist/Tools/PlistBuddy.cpp

- Use (const) pointers instead of references to match existing style.
- Replace switches on types with casting, reduce switch nesting.

Minor cleanups to previous commit.

---

Specifications/Compiler/com.apple.compilers.llvm.clang.1_0.analyzer.xcspec
Specifications/Compiler/com.apple.compilers.llvm.clang.1_0.astbuilder.xcspec
Specifications/Compiler/com.apple.compilers.llvm.clang.1_0.migrator.xcspec
Specifications/Compiler/com.apple.compilers.llvm.clang.1_0.migrator.xctest.xcspec
Specifications/Compiler/com.apple.compilers.model.coredata.xcspec
Specifications/Compiler/com.apple.compilers.model.coredatamapping.xcspec
Specifications/FileType/CMakeLists.txt
Specifications/Tool/com.apple.build-tools.strip.xcspec
Specifications/Tool/com.apple.commands.built-in.validate.xcspec

- Complete strip and product validation specification options.
- Fix typo in specification property and file type listing.
- Minor formatting adjustments to a few specifications.
cc @onhachoe

Minor specification additions & cleanups.

---

Specifications/Compiler/CMakeLists.txt

Add copy-{tiff,png}-file.xcspec to CMakeFiles.txt

---

Libraries/xcdriver/Sources/BuildAction.cpp
Libraries/xcexecution/CMakeLists.txt
Libraries/xcexecution/Headers/xcexecution/SimpleExecutor.h
Libraries/xcexecution/Sources/SimpleExecutor.cpp
Libraries/xcexecution/Tests/test_SimpleExecutor.cpp
Libraries/xcformatter/CMakeLists.txt
Libraries/xcformatter/Headers/xcformatter/NullFormatter.h
Libraries/xcformatter/Sources/NullFormatter.cpp

Fixes #175 and starts looking into how to test highly integrated components like this.

Fix and unit test for simple executor.

---

Specifications/Compiler/CMakeLists.txt
Specifications/Compiler/com.apple.build-tools.nmedit.xcspec
Specifications/Compiler/com.apple.compilers.lex.xcspec
Specifications/Compiler/com.apple.compilers.resource-copier.xcspec
Specifications/Compiler/com.apple.compilers.yacc.xcspec

Adds:
- com.apple.build-tools.nmedit
- com.apple.compilers.lex
- com.apple.compilers.resource-copier
- com.apple.compilers.yacc

Add more xcspecs.

---

Libraries/plist/Tools/plutil.cpp

Also, fix default output format when performing modifications without
conversion. It would always fail due to not having a target format.

Support reading JSON (as well as writing) in property list utility.

---

Libraries/pbxspec/Sources/Manager.cpp

@matthewbauer This should fix your issue — let me know if it doesn't. @Ktwu, curious if this helps with #195 at all.

Support loading specifications from a directory symlink.

---

Libraries/libbom/Tools/lsbom.cpp

Short options can be combined and used as a single flag. For split
short options, the value can follow in a combined option or in the
next option.

Support short options in lsbom.

---

Libraries/pbxbuild/Sources/Phase/FrameworksResolver.cpp

This fixes expanding OutputPath properly for dsymutil, fixing
issue #208.

Resolve the dsymutil tool invocation in the right way

---

Libraries/xcdriver/Sources/VersionAction.cpp

Implements missing feature from #204.

Add support for printing specific information with version option.

---

Specifications/Compiler/CMakeLists.txt
Specifications/Compiler/com.apple.xcode.tools.ibtool.compiler.xcspec
Specifications/Compiler/com.apple.xcode.tools.ibtool.storyboard.compiler.xcspec
Specifications/Compiler/com.apple.xcode.tools.ibtool.storyboard.linker.xcspec

basic ibtool xib/storyboard compilation actions

add xcspecs for ibtool operations

---

Specifications/Compiler/com.apple.xcode.tools.ibtool.storyboard.linker.xcspec

ibtool storyboard linker xcspec typo fix

---

Libraries/process/Sources/DefaultLauncher.cpp

We didn't setup pipe to receive output of execve, which caused problems
as xcbuild and launched task would try to write to stdout/stderr unsynchronized.
Fix this by piping in output from child task, and manually printing them from xcbuild itself.

Get stdout/stderr of launched task with pipe.

---

Libraries/plist/Tools/PlistBuddy.cpp

Check input to determine the save format, and if not found,
make XML the default save format.
Print format logic stays the same.

Make PlistBuddy differentiate save and print format

---

Libraries/libbom/Sources/bom_memory.c

These commits fix the issues reported in issue #268.

Windows fixes

---

Libraries/libutil/Sources/DefaultFilesystem.cpp
Libraries/process/Sources/DefaultContext.cpp

- I'm dumb; I forgot to concatenate expanded symlink values together
- I also misused the shell expansion API; fixed that too

Fix bugs in previous symlink / environment expansion
